name: KPMUpdater
version: ${project.version}
main: net.kunmc.lab.kpmupdater.KPMUpdater
api-version: 1.16
authors: [Peyang]
description: Update KPM
website: https://kunmc.net/

commands:
  kpmupdate:
    description: KPMをアップデートします。
